// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieGalleryAPI.Data;

#nullable disable

namespace MovieGalleryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830101429_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieGalleryAPI.Model.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "Matt Damon, Anne Hathaway",
                            Description = "Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.",
                            Director = "Christopher Nolan",
                            Genre = "Adventure",
                            PopularityScore = 98,
                            PosterUrl = "https://image.tmdb.org/t/p/original/pe5cCoX5iIb5IWKPsbPkCwjLFHt.jpg",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 2026,
                            Title = "The Odyssey",
                            TmdbId = 1368337
                        },
                        new
                        {
                            Id = 2,
                            Cast = "Michael Johnston, Inde Navarette",
                            Description = "After breaking the mysterious “One Wish Willow” to win his crush’s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.",
                            Director = "Curry Barker",
                            Genre = "Horror",
                            PopularityScore = 97,
                            PosterUrl = "https://image.tmdb.org/t/p/original/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
                            Rating = 8.1999999999999993,
                            ReleaseYear = 2025,
                            Title = "Obsession",
                            TmdbId = 1339713
                        },
                        new
                        {
                            Id = 3,
                            Cast = "Michael Cera, Mary Elizabeth Winstead",
                            Description = "As bass guitarist for a garage-rock band, Scott Pilgrim has never had trouble getting a girlfriend; usually, the problem is getting rid of them. But when Ramona Flowers skates into his heart, he finds she has the most troublesome baggage of all: an army of ex-boyfriends who will stop at nothing to eliminate him from her list of suitors.",
                            Director = "Edgar Wright",
                            Genre = "Comedy",
                            PopularityScore = 87,
                            PosterUrl = "https://image.tmdb.org/t/p/original/g5IoYeudx9XBEfwNL0fHvSckLBz.jpg",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2010,
                            Title = "Scott Pilgrim vs. the World",
                            TmdbId = 22538
                        },
                        new
                        {
                            Id = 4,
                            Cast = "David Corenswet, Rachel Brosnahan",
                            Description = "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
                            Director = "James Gunn",
                            Genre = "Action",
                            PopularityScore = 89,
                            PosterUrl = "https://image.tmdb.org/t/p/original/wPLysNDLffQLOVebZQCbXJEv6E6.jpg",
                            Rating = 8.4000000000000004,
                            ReleaseYear = 2025,
                            Title = "Superman",
                            TmdbId = 1061474
                        },
                        new
                        {
                            Id = 5,
                            Cast = "Tom Hanks, Robin Wright",
                            Description = "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
                            Director = "Robert Zemeckis",
                            Genre = "Drama",
                            PopularityScore = 92,
                            PosterUrl = "https://image.tmdb.org/t/p/original/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 1994,
                            Title = "Forrest Gump",
                            TmdbId = 13
                        },
                        new
                        {
                            Id = 6,
                            Cast = "Keanu Reeves, Laurence Fishburne",
                            Description = "A hacker learns the truth about his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski",
                            Genre = "Sci-Fi",
                            PopularityScore = 91,
                            PosterUrl = "https://image.tmdb.org/t/p/original/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 1999,
                            Title = "The Matrix",
                            TmdbId = 603
                        },
                        new
                        {
                            Id = 7,
                            Cast = "Tom Holland, Zendaya",
                            Description = "Fighting crime full-time as Spider-Man in a world that doesn’t remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
                            Director = "Destin Daniel Cretton",
                            Genre = "Action",
                            PopularityScore = 90,
                            PosterUrl = "https://image.tmdb.org/t/p/original/kt3IvI7VDffMFMcQzn8AIi1m2zI.jpg",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2026,
                            Title = "Spider-Man: Brand New Day",
                            TmdbId = 969681
                        },
                        new
                        {
                            Id = 8,
                            Cast = "Marlon Brando, Al Pacino",
                            Description = "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            PopularityScore = 96,
                            PosterUrl = "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            Rating = 9.1999999999999993,
                            ReleaseYear = 1972,
                            Title = "The Godfather",
                            TmdbId = 238
                        },
                        new
                        {
                            Id = 9,
                            Cast = "Brad Pitt, Edward Norton",
                            Description = "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
                            Director = "David Fincher",
                            Genre = "Drama",
                            PopularityScore = 89,
                            PosterUrl = "https://image.tmdb.org/t/p/original/wR5HZWdVpcXx9sevV1bQi7rP4op.jpg",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 1999,
                            Title = "Fight Club",
                            TmdbId = 550
                        },
                        new
                        {
                            Id = 10,
                            Cast = "Rumi Hiiragi, Miyu Irino",
                            Description = "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            PopularityScore = 88,
                            PosterUrl = "https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
                            Rating = 8.5999999999999996,
                            ReleaseYear = 2001,
                            Title = "Spirited Away",
                            TmdbId = 129
                        },
                        new
                        {
                            Id = 11,
                            Cast = "Yuumi kawai, Mizuki Yoshida",
                            Description = "Popular, outgoing Fujino is celebrated by her classmates for her funny comics in the class newspaper. One day, her teacher asks her to share the space with Kyomoto, a truant recluse whose beautiful artwork sparks a competitive fervor in Fujino. What starts as jealousy transforms when Fujino realizes their shared passion for drawing.",
                            Director = "Kiyotaka Oshiyama",
                            Genre = "Animation",
                            PopularityScore = 87,
                            PosterUrl = "https://image.tmdb.org/t/p/original/4f2EcNkp1Mvp9wE5w7HKxcmACWg.jpg",
                            Rating = 8.5,
                            ReleaseYear = 2024,
                            Title = "Look Back",
                            TmdbId = 1244492
                        },
                        new
                        {
                            Id = 12,
                            Cast = "Kyoko Fukada, Anna Tsuchiya",
                            Description = "Momoko, a strange and seemingly emotionless girl obsessed with 18th century France, befriends a Yanki biker and the two experience the ups and downs of their unusual lives in a rural Japanese town.",
                            Director = "Tetsuya Nakashima",
                            Genre = "Comedy",
                            PopularityScore = 85,
                            PosterUrl = "https://image.tmdb.org/t/p/original/43kZBGCXQbydXTDjRuuLTfwpQXh.jpg",
                            Rating = 7.2000000000000002,
                            ReleaseYear = 2004,
                            Title = "Kamikaze Girls",
                            TmdbId = 26275
                        });
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.MovieScreenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenshots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/shawshank-shot1/800/450",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/shawshank-shot2/800/450",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/shawshank-shot3/800/450",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/darkknight-shot1/800/450",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/darkknight-shot2/800/450",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/darkknight-shot3/800/450",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/inception-shot1/800/450",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/inception-shot2/800/450",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/inception-shot3/800/450",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/pulpfiction-shot1/800/450",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/pulpfiction-shot2/800/450",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/pulpfiction-shot3/800/450",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/forrestgump-shot1/800/450",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/forrestgump-shot2/800/450",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/forrestgump-shot3/800/450",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/matrix-shot1/800/450",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/matrix-shot2/800/450",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/matrix-shot3/800/450",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/interstellar-shot1/800/450",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/interstellar-shot2/800/450",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/interstellar-shot3/800/450",
                            MovieId = 7
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/godfather-shot1/800/450",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/godfather-shot2/800/450",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/godfather-shot3/800/450",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/fightclub-shot1/800/450",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/fightclub-shot2/800/450",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/fightclub-shot3/800/450",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/spiritedaway-shot1/800/450",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/spiritedaway-shot2/800/450",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/spiritedaway-shot3/800/450",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/parasite-shot1/800/450",
                            MovieId = 11
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/parasite-shot2/800/450",
                            MovieId = 11
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/parasite-shot3/800/450",
                            MovieId = 11
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 1,
                            ImageUrl = "https://picsum.photos/seed/gladiator-shot1/800/450",
                            MovieId = 12
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 2,
                            ImageUrl = "https://picsum.photos/seed/gladiator-shot2/800/450",
                            MovieId = 12
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 3,
                            ImageUrl = "https://picsum.photos/seed/gladiator-shot3/800/450",
                            MovieId = 12
                        });
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.Favorite", b =>
                {
                    b.HasOne("MovieGalleryAPI.Model.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieGalleryAPI.Model.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.MovieScreenshot", b =>
                {
                    b.HasOne("MovieGalleryAPI.Model.Movie", "Movie")
                        .WithMany("Screenshots")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.Movie", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("MovieGalleryAPI.Model.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
